name: ${name}
version: ${version}
main: ${main}
api-version: "${apiVersion}"
description: Cross-platform Minecraft plugin framework providing unified abstractions
author: Supatuck
website: https://github.com/PCX-Network/UnifiedPlugin-API
folia-supported: true

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    LuckPerms:
      load: BEFORE
      required: false
